name: Sandbox
on: [push]
jobs:
    test-sandbox:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
              with:
                  repository: near/nearcore
            - uses: actions/cache@v2
              id: sandbox-cache  # give it a name for checking the cache hit-or-not
              with:
                path: ./target/  # what we cache: the folder
                key: sandbox-cache
            - name: "Building near"
              run: make sandbox
              if: steps.sandbox-cache.outputs.cache-hit != 'true'
            - name: 'Building near'
              working-directory: ./
              run: |
                  rm -rf /tmp/near-sandbox
                  target/debug/near-sandbox --home /tmp/near-sandbox init
